const SHORT_ANSWER = "SHORT_ANSWER";
const PARAGRAPH = "PARAGRAPH";
const MULTIPLE_CHOICE = "MULTIPLE_CHOICE";
const CHECKBOXES = "CHECKBOXES";
const DROPDOWN = "DROPDOWN";
const FILE_UPLOAD = "FILE_UPLOAD";
const DATE = "DATE";
const TIME = "TIME";
const FILL_WORD = "FILL_WORD";
const DRAGGABLE = "DRAGGABLE";
const RATING = "RATING";

export {
    SHORT_ANSWER,
    PARAGRAPH,
    MULTIPLE_CHOICE,
    CHECKBOXES,
    DROPDOWN,
    FILE_UPLOAD,
    DATE,
    TIME,
    FILL_WORD,
    DRAGGABLE,
    RATING
}