export const khaoSat1Tag = [
  "Thích giao tiếp",
  "Trầm tư",
  "Hấp dẫn",
  "Ngăn nắp",
  "Kiên định",
  "Chắc chắn",
  "Kiên nhẫn",
  "Thấu hiểu",
  "Phản ứng nhanh",
  "Hợp lý",
  "Liều lĩnh",
  "Thận trọng",
  "Vui vẻ",
  "Kiểu truyền thống",
  "Có nhận thức",
  "Kiên trì",
  "Có sức hút",
  "Bền bỉ",
  "Óc thực tế",
  "Thuyết phục",
  "Quyến rũ",
  "Thư thái",
  "Tao nhã",
  "Có lý",
  "Kiểm soát",
  "Chu đáo",
  "Hiền lành",
  "Có óc phân tích",
  "Hình thức",
  "Cạnh tranh",
  "Hài lòng",
  "Trung thành",
  "Có tổ chức",
  "Thú vị",
  "Cảnh giác",
  "Năng nổ",
  "Trầm tính",
  "Được yêu mến",
  "Tư duy logic",
  "Khiêm tốn",
  "Uy quyền",
  "Đúng đắn",
  "Nghiêm túc",
  "Biết cảm thông",
  "Nổi bật",
  "Quyết đoán",
  "Kỹ tính",
  "Kiên quyết",
  "Có kỷ luật",
  "Có trách nhiệm",
  "Hòa thuận",
  "Duyên dáng",
  "Chính xác",
  "Nghiêm chỉnh",
  "Có trật tự",
  "Có quyền lực",
  "Tốt",
  "Khoan dung",
  "Háo hức",
  "Lôi cuốn",
  "Nguyên tắc",
  "Can đảm",
  "Ổn định",
  "Dễ thương",
  "Dễ chịu",
  "Có ảnh hưởng",
  "Có óc quan sát",
  "Trung thực",
  "Nghiêm nghị",
  "Trước sau như một",
  "Lịch sự",
  "Dễ gần",
  "Điềm tĩnh",
  "Quả quyết",
  "Biết kính trọng",
  "Gọn gàng",
  "Nói nhiều",
  "Kín đáo",
  "Có suy xét",
  "Táo bạo",
  "Cởi mở",
  "Tỉ mỉ",
  "Được kính trọng",
  "Dễ tính",
  "Quyết liệt",
  "Khách quan",
];
export const KhaoSat2Tag = [
  "Thích giao tiếp",
  "Trầm tư",
  "Hấp dẫn",
  "Ngăn nắp",
  "Kiên định",
  "Chắc chắn",
  "Kiên nhẫn",
  "Thấu hiểu",
  "Phản ứng nhanh",
  "Hợp lý",
  "Liều lĩnh",
  "Thận trọng",
  "Vui vẻ",
  "Kiểu truyền thống",
  "Có nhận thức",
  "Kiên trì",
  "Có sức hút",
  "Bền bỉ",
  "Óc thực tế",
  "Thuyết phục",
  "Quyến rũ",
  "Thư thái",
  "Tao nhã",
  "Có lý",
  "Kiểm soát",
  "Chu đáo",
  "Hiền lành",
  "Có óc phân tích",
  "Hình thức",
  "Cạnh tranh",
  "Hài lòng",
  "Trung thành",
  "Có tổ chức",
  "Thú vị",
  "Cảnh giác",
  "Năng nổ",
  "Trầm tính",
  "Được yêu mến",
  "Tư duy logic",
  "Khiêm tốn",
  "Uy quyền",
  "Đúng đắn",
  "Nghiêm túc",
  "Biết cảm thông",
  "Nổi bật",
  "Quyết đoán",
  "Kỹ tính",
  "Kiên quyết",
  "Có kỷ luật",
  "Có trách nhiệm",
  "Hòa thuận",
  "Duyên dáng",
  "Chính xác",
  "Nghiêm chỉnh",
  "Có trật tự",
  "Có quyền lực",
  "Tốt",
  "Khoan dung",
  "Háo hức",
  "Lôi cuốn",
  "Nguyên tắc",
  "Can đảm",
  "Ổn định",
  "Dễ thương",
  "Dễ chịu",
  "Có ảnh hưởng",
  "Có óc quan sát",
  "Trung thực",
  "Nghiêm nghị",
  "Trước sau như một",
  "Lịch sự",
  "Dễ gần",
  "Điềm tĩnh",
  "Quả quyết",
  "Biết kính trọng",
  "Gọn gàng",
  "Nói nhiều",
  "Kín đáo",
  "Có suy xét",
  "Táo bạo",
  "Cởi mở",
  "Tỉ mỉ",
  "Được kính trọng",
  "Dễ tính",
  "Quyết liệt",
  "Khách quan",
];
