//Nguoi Dung 
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const LAY_DANH_SACH_NGUOI_DUNG_ACTION = "LAY_DANH_SACH_NGUOI_DUNG_ACTION";

export const THEM_NGUOI_DUNG = "THEM_NGUOI_DUNG";

export const LAY_NGUOI_DUNG_EMAIL = "LAY_NGUOI_DUNG_EMAIL";
export const LAY_NGUOI_DUNG_EMAIL_ACTION = "LAY_NGUOI_DUNG_EMAIL_ACTION";

export const LAY_NGUOI_DUNG_SO_DT = "LAY_NGUOI_DUNG_SO_DT";

export const LAY_NGUOI_DUNG_ID = "LAY_NGUOI_DUNG_ID";
export const LAY_NGUOI_DUNG_ID_ACTION = "LAY_NGUOI_DUNG_ID_ACTION";

export const UPLOAD_CMND = "UPLOAD_CMND";

export const NOP_BAI_TEST_USER = "NOP_BAI_TEST_USER";

//Lo trinh
export const LAY_DANH_SACH_LO_TRINH = "LAY_DANH_SACH_LO_TRINH";
export const LAY_DANH_SACH_LO_TRINH_ACTION = "LAY_DANH_SACH_LO_TRINH_ACTION";

export const THEM_LO_TRINH = "THEM_LO_TRINH";
export const THEM_LO_TRINH_ACTION = "THEM_LO_TRINH_ACTION";

//khoa hoc
export const LAY_THOI_LUONG_KHOA_HOC = "LAY_THOI_LUONG_KHOA_HOC";

export const LAY_DANH_SACH_KHOA_HOC = "LAY_DANH_SACH_KHOA_HOC";
export const LAY_DANH_SACH_KHOA_HOC_ACTION = "LAY_DANH_SACH_KHOA_HOC_ACTION";

export const LAY_CHI_TIET_KHOA_HOC = "LAY_CHI_TIET_KHOA_HOC";
export const LAY_CHI_TIET_KHOA_HOC_ACTION = "LAY_CHI_TIET_KHOA_HOC_ACTION";

//tien trinh hoc

export const LAY_DANH_SACH_TIEN_TRINH_HOC_ACTION = "LAY_DANH_SACH_TIEN_TRINH_HOC_ACTION";
export const LAY_DANH_SACH_TIEN_TRINH_HOC = "LAY_DANH_SACH_TIEN_TRINH_HOC";

//lich su tuong tac
export const LAY_LICH_SU_TUONG_TAC_ACTION = "LAY_LICH_SU_TUONG_TAC_ACTION";
export const LAY_LICH_SU_TUONG_TAC = "LAY_LICH_SU_TUONG_TAC";

export const LAY_LICH_SU_TUONG_TAC_THEO_USER_ACTION = "LAY_LICH_SU_TUONG_TAC_THEO_USER_ACTION";
export const LAY_LICH_SU_TUONG_TAC_THEO_USER = "LAY_LICH_SU_TUONG_TAC_THEO_USER";


//bai hoc
export const LAY_DANH_SACH_BAI_HOC_ACTION = "LAY_DANH_SACH_BAI_HOC_ACTION";
export const LAY_DANH_SACH_BAI_HOC = "LAY_DANH_SACH_BAI_HOC";

//thao luan
export const LAY_DANH_SACH_THAO_LUAN_ACTION = "LAY_DANH_SACH_THAO_LUAN_ACTION";
export const LAY_DANH_SACH_THAO_LUAN = "LAY_DANH_SACH_THAO_LUAN";

// lich su hoc tap
export const LAY_TAT_CA_LICH_SU_HOC_TAP = "LAY_TAT_CA_LICH_SU_HOC_TAP";
export const LAY_TAT_CA_LICH_SU_HOC_TAP_THANH_CONG = "LAY_TAT_CA_LICH_SU_HOC_TAP_THANH_CONG";

export const LAY_LICH_SU_HOC_TAP = "LAY_LICH_SU_HOC_TAP";
export const LAY_LICH_SU_HOC_TAP_THANH_CONG = "LAY_LICH_SU_HOC_TAP_THANH_CONG";

export const CAP_NHAT_LICH_SU_HOC_TAP = "CAP_NHAT_LICH_SU_HOC_TAP";
export const CAP_NHAT_LICH_SU_HOC_TAP_THANH_CONG = "CAP_NHAT_LICH_SU_HOC_TAP_THANH_CONG";

export const CAP_NHAT_BAI_DA_HOC = "CAP_NHAT_BAI_DA_HOC";
export const CAP_NHAT_BAI_DA_HOC_THANH_CONG = "CAP_NHAT_BAI_DA_HOC_THANH_CONG";


// bai nop

export const LAY_DANH_SACH_NOP_BAI_ACTION = "LAY_DANH_SACH_NOP_BAI_ACTION";
export const LAY_DANH_SACH_NOP_BAI = "LAY_DANH_SACH_NOP_BAI";


//chuong hoc 
export const LAY_DANH_SACH_CHUONG_ACTION = "LAY_DANH_SACH_CHUONG_ACTION";
export const LAY_DANH_SACH_CHUONG = "LAY_DANH_SACH_CHUONG";

//danh gia 
export const LAY_DANH_SACH_DANH_GIA_KHOA_HOC_ACTION = "LAY_DANH_SACH_DANH_GIA_KHOA_HOC_ACTION";
export const LAY_DANH_SACH_DANH_GIA_KHOA_HOC = "LAY_DANH_SACH_DANH_GIA_KHOA_HOC";

export const LAY_DANH_SACH_DANH_GIA_MENTOR_ACTION = "LAY_DANH_SACH_DANH_GIA_MENTOR_ACTION";
export const LAY_DANH_SACH_DANH_GIA_MENTOR = "LAY_DANH_SACH_DANH_GIA_MENTOR";


export const LAY_DANH_SACH_LOAI_KHOA_HOC_ACTION = "LAY_DANH_SACH_LOAI_KHOA_HOC_ACTION";
export const LAY_DANH_SACH_LOAI_KHOA_HOC = "LAY_DANH_SACH_LOAI_KHOA_HOC";

//hop thu 
export const LAY_DANH_SACH_HOP_THU_ACTION = "LAY_DANH_SACH_HOP_THU_ACTION";
export const LAY_DANH_SACH_HOP_THU = "LAY_DANH_SACH_HOP_THU";


//bai tap
export const LAY_BAI_TAP_ACTION = "LAY_BAI_TAP_ACTION";
export const LAY_BAI_TAP = "LAY_BAI_TAP";

//QA
export const LAY_DANH_SACH_QA_ACTION = "LAY_DANH_SACH_QA_ACTION";
export const LAY_DANH_SACH_QA = "LAY_DANH_SACH_QA";


